local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local trainstationutil = require "modules/trainstationutil"

function data()
    return {
        cost = {
            price = -1,
        },
        category = {
            categories = { "passenger buildings", "PDL", },
        },
        description = {
            name = _("Gare d'Ancenis'"),
            --description = _("Gare de Nantes Nord"),
            icon = "ui/models_small/construction/station/rail/modular_station/ancenis.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "rail_side_building_size1",
        order = {
            value = 3501,
        },
        metadata = {
            era = 0,
            level =2,
            span = {0, 2},
            moreCapacity = {
                cargo = 0,
                passenger = 80
            }
        },
        updateFn = function(result, transform, tag, slotId, addModuleFn, params)
            local config = {
                extend = { -18.01, 17.99, -6.15, 6.15, 0, 15.58 },
                main = "station/train/ancenis.mdl",

                slotIdOffset = 5,
                translationY = 0,
            }
            trainstationutil.MakeMainBuildingModule(result, transform, tag, slotId, addModuleFn, params, config)
        end,
        getModelsFn = function()
		
            local result = {
                { 
                    id = "station/train/ancenis.mdl",
                    transf = transf.rotZTransl(math.rad(-90), vec3.new(10,0,-12)),
                },
            }
            
            return result
        end
    }
end